bump_version: null
lint:
  files_exist:
    - conf/igenomes.config
  files_unchanged:
    - .github/CONTRIBUTING.md
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: itrujnara
  description: A pipeline for ortholog fetching and analysis
  force: false
  is_nfcore: true
  name: reportho
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.1.0dev
update: null
